### ISSUE TITLE
Volume Add 

### ISSUE THREAD

**Issue by rawstorage** [rawstorage/dellemcpmax_ansible#48]
Unit_Test reveals issue with adding devices of different label,  bug introduced with idempotency changes and must have been overlooked..   Module still produces correct number of devices however labels don't match with the volume request.

PLAYBOOK: storagegroup_module_unit_tests.yml ******************************************************************************************************************
1 plays in ./storagegroup_module_unit_tests.yml
Read vars_file 'vars.yml'
Read vars_file 'vars.yml'
Read vars_file 'vars.yml'

PLAY [Provision a new storage group] **************************************************************************************************************************
META: ran handlers
Read vars_file 'vars.yml'

TASK [Create Storage Group] ***********************************************************************************************************************************
task path: /mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/storagegroup_module_unit_tests.yml:72
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martip5
<127.0.0.1> EXEC /bin/sh -c 'echo ~martip5 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229 `" && echo ansible-tmp-1558348316.73-265666053360229="` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/dellemc/dellemc_pmax_storagegroup.py
<127.0.0.1> PUT /home/martip5/.ansible/tmp/ansible-local-3765IeaPPu/tmpvA8XKB TO /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229/AnsiballZ_dellemc_pmax_storagegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229/ /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martip5/.ansible/tmp/ansible-tmp-1558348316.73-265666053360229/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "ansible_facts": {
        "storagegroup_detail": {
            "lun_request": [
                {
                    "cap_gb": 1, 
                    "num_vols": 1
                }
            ], 
            "message": [
                "Empty Storage Group Ansible_UnitTest_SG Created", 
                "SLO of SG Ansible_UnitTest_SG already Diamond", 
                "1 volume(s) of 1 GB added"
            ], 
            "sg_volumes": [
                {
                    "cap_gb": 1.0, 
                    "vol_name": "DATA", 
                    "volumeId": "000BD", 
                    "wwn": "60000970000197600156533030304244"
                }
            ], 
            "storagegroup_name": "Ansible_UnitTest_SG"
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "array_id": "000197600156", 
            "luns": [
                {
                    "cap_gb": 1, 
                    "num_vols": 1, 
                    "vol_name": "DATA"
                }
            ], 
            "new_sgname": null, 
            "no_compression": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "sgname": "Ansible_UnitTest_SG", 
            "slo": "Diamond", 
            "state": "present", 
            "unispherehost": "IPaddress", 
            "universion": 90, 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verifycert": false
        }
    }, 
    "state": "info"
}
Read vars_file 'vars.yml'

TASK [Add Redo Volume] ****************************************************************************************************************************************
task path: /mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/storagegroup_module_unit_tests.yml:79
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martip5
<127.0.0.1> EXEC /bin/sh -c 'echo ~martip5 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875 `" && echo ansible-tmp-1558348332.1-64318904337875="` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/dellemc/dellemc_pmax_storagegroup.py
<127.0.0.1> PUT /home/martip5/.ansible/tmp/ansible-local-3765IeaPPu/tmpr2yYbp TO /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875/AnsiballZ_dellemc_pmax_storagegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875/ /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martip5/.ansible/tmp/ansible-tmp-1558348332.1-64318904337875/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "ansible_facts": {
        "storagegroup_detail": {
            "lun_request": [
                {
                    "cap_gb": 1, 
                    "num_vols": 2
                }
            ], 
            "message": [
                "SG Ansible_UnitTest_SG already exists", 
                "SLO of SG Ansible_UnitTest_SG already Diamond", 
                "1 volume(s) of 1 GB added"
            ], 
            "sg_volumes": [
                {
                    "cap_gb": 1.0, 
                    "vol_name": "DATA", 
                    "volumeId": "000BD", 
                    "wwn": "60000970000197600156533030304244"
                }, 
                {
                    "cap_gb": 1.0, 
                    "vol_name": "REDO", 
                    "volumeId": "000BE", 
                    "wwn": "60000970000197600156533030304245"
                }
            ], 
            "storagegroup_name": "Ansible_UnitTest_SG"
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "array_id": "000197600156", 
            "luns": [
                {
                    "cap_gb": 1, 
                    "num_vols": 1, 
                    "vol_name": "DATA"
                }, 
                {
                    "cap_gb": 1, 
                    "num_vols": 1, 
                    "vol_name": "REDO"
                }
            ], 
            "new_sgname": null, 
            "no_compression": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "sgname": "Ansible_UnitTest_SG", 
            "slo": "Diamond", 
            "state": "present", 
            "unispherehost": "IPaddress", 
            "universion": 90, 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verifycert": false
        }
    }, 
    "state": "info"
}
Read vars_file 'vars.yml'

TASK [Add additional Data Volume] *****************************************************************************************************************************
task path: /mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/storagegroup_module_unit_tests.yml:86
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martip5
<127.0.0.1> EXEC /bin/sh -c 'echo ~martip5 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656 `" && echo ansible-tmp-1558348344.71-18712562477656="` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/dellemc/dellemc_pmax_storagegroup.py
<127.0.0.1> PUT /home/martip5/.ansible/tmp/ansible-local-3765IeaPPu/tmpLh2qrX TO /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656/AnsiballZ_dellemc_pmax_storagegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656/ /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martip5/.ansible/tmp/ansible-tmp-1558348344.71-18712562477656/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "ansible_facts": {
        "storagegroup_detail": {
            "lun_request": [
                {
                    "cap_gb": 1, 
                    "num_vols": 3
                }
            ], 
            "message": [
                "SG Ansible_UnitTest_SG already exists", 
                "SLO of SG Ansible_UnitTest_SG already Diamond", 
                "1 volume(s) of 1 GB added"
            ], 
            "sg_volumes": [
                {
                    "cap_gb": 1.0, 
                    "vol_name": "DATA", 
                    "volumeId": "000BD", 
                    "wwn": "60000970000197600156533030304244"
                }, 
                {
                    "cap_gb": 1.0, 
                    "vol_name": "REDO", 
                    "volumeId": "000BE", 
                    "wwn": "60000970000197600156533030304245"
                }, 
                {
                    "cap_gb": 1.0,
                    "vol_name": "REDO",   << New volume added with REDO Label instead of DATA
                    "volumeId": "000BF", 
                    "wwn": "60000970000197600156533030304246"
                }
            ], 
            "storagegroup_name": "Ansible_UnitTest_SG"
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "array_id": "000197600156", 
            "luns": [
                {
                    "cap_gb": 1, 
                    "num_vols": 2, 
                    "vol_name": "DATA"
                }, 
                {
                    "cap_gb": 1, 
                    "num_vols": 1, 
                    "vol_name": "REDO"
                }
            ], 
            "new_sgname": null, 
            "no_compression": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "sgname": "Ansible_UnitTest_SG", 
            "slo": "Diamond", 
            "state": "present", 
            "unispherehost": "IPaddress", 
            "universion": 90, 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verifycert": false
        }
    }, 
    "state": "info"
}
Read vars_file 'vars.yml'

TASK [Add additional Redo Volume] *****************************************************************************************************************************
task path: /mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/storagegroup_module_unit_tests.yml:93
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martip5
<127.0.0.1> EXEC /bin/sh -c 'echo ~martip5 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590 `" && echo ansible-tmp-1558348357.4-21199161725590="` echo /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/dellemc/dellemc_pmax_storagegroup.py
<127.0.0.1> PUT /home/martip5/.ansible/tmp/ansible-local-3765IeaPPu/tmpTj7d0d TO /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590/AnsiballZ_dellemc_pmax_storagegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590/ /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590/AnsiballZ_dellemc_pmax_storagegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martip5/.ansible/tmp/ansible-tmp-1558348357.4-21199161725590/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "ansible_facts": {
        "storagegroup_detail": {
            "lun_request": [
                {
                    "cap_gb": 1, 
                    "num_vols": 4
                }
            ], 
            "message": [
                "SG Ansible_UnitTest_SG already exists", 
                "SLO of SG Ansible_UnitTest_SG already Diamond", 
                "1 volume(s) of 1 GB added"
            ], 
            "sg_volumes": [
                {
                    "cap_gb": 1.0, 
                    "vol_name": "DATA", 
                    "volumeId": "000BD", 
                    "wwn": "60000970000197600156533030304244"
                }, 
                {
                    "cap_gb": 1.0, 
                    "vol_name": "REDO", 
                    "volumeId": "000BE", 
                    "wwn": "60000970000197600156533030304245"
                }, 
                {
                    "cap_gb": 1.0, 
                    "vol_name": "REDO", 
                    "volumeId": "000BF", 
                    "wwn": "60000970000197600156533030304246"
                }, 
                {
                    "cap_gb": 1.0, 
                    "vol_name": "REDO", 
                    "volumeId": "000C0", 
                    "wwn": "60000970000197600156533030304330"
                }
            ], 
            "storagegroup_name": "Ansible_UnitTest_SG"
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "array_id": "000197600156", 
            "luns": [
                {
                    "cap_gb": 1, 
                    "num_vols": 2, 
                    "vol_name": "DATA"
                }, 
                {
                    "cap_gb": 1, 
                    "num_vols": 2, 
                    "vol_name": "REDO"
                }
            ], 
            "new_sgname": null, 
            "no_compression": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "sgname": "Ansible_UnitTest_SG", 
            "slo": "Diamond", 
            "state": "present", 
            "unispherehost": "IPaddress", 
            "universion": 90, 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verifycert": false
        }
    }, 
    "state": "info"
}
Read vars_file 'vars.yml'

**Comment by rawstorage** [comment]
Julien, I'll assign this bug to you.  Reach out if you need clarification on the issue I've marked up the output in the unit_test.  Note PR 46 is merged to Development branch

**Comment by jbrt** [comment]
Hi @rawstorage,

Sorry for this late answer, I've focused on another projects this last weeks. I'll check that point and I go back to you soon.

Have a nice day,
Regards,

**Comment by jbrt** [comment]
Hi again @rawstorage,

I can't reproduce the bug on my side, while I'm running the unitest playbook, the expected behavior seems to be OK.

Can you please send me your custom Ansible vars ? 

PLAY [Provision a new storage group] *********************************************************************************************************************

TASK [Create new empty Storage Group] ********************************************************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [],
        "message": [
            "Empty Storage Group Ansible_SG_testing Created",
            "SLO of SG Ansible_SG_testing already Diamond"
        ],
        "sg_volumes": [],
        "storagegroup_name": "Ansible_SG_testing"
    }
}

TASK [(Idempotency check) Create new empty Storage Group] ************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [],
        "message": [
            "SG Ansible_SG_testing already exists",
            "SLO of SG Ansible_SG_testing already Diamond"
        ],
        "sg_volumes": [],
        "storagegroup_name": "Ansible_SG_testing"
    }
}

TASK [Adding volumes to this Storage Group] **************************************************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [
            {
                "cap_gb": 1,
                "num_vols": 1
            },
            {
                "cap_gb": 2,
                "num_vols": 1
            }
        ],
        "message": [
            "SG Ansible_SG_testing already exists",
            "SLO of SG Ansible_SG_testing already Diamond",
            "1 volume(s) of 2 GB added",
            "1 volume(s) of 1 GB added"
        ],
        "sg_volumes": [
            {
                "cap_gb": 2.0,
                "vol_name": "DATA",
                "volumeId": "000F5",
                "wwn": "60000970000297800941533030304635"
            },
            {
                "cap_gb": 1.0,
                "vol_name": "REDO",
                "volumeId": "000F6",
                "wwn": "60000970000297800941533030304636"
            }
        ],
        "storagegroup_name": "Ansible_SG_testing"
    }
}

TASK [(Idempotency check) Adding volumes to this Storage Group] ******************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [
            {
                "cap_gb": 1,
                "num_vols": 1
            },
            {
                "cap_gb": 2,
                "num_vols": 1
            }
        ],
        "message": [
            "SG Ansible_SG_testing already exists",
            "SLO of SG Ansible_SG_testing already Diamond"
        ],
        "sg_volumes": [
            {
                "cap_gb": 2.0,
                "vol_name": "DATA",
                "volumeId": "000F5",
                "wwn": "60000970000297800941533030304635"
            },
            {
                "cap_gb": 1.0,
                "vol_name": "REDO",
                "volumeId": "000F6",
                "wwn": "60000970000297800941533030304636"
            }
        ],
        "storagegroup_name": "Ansible_SG_testing"
    }
}

TASK [Adding volumes just a few volumes to this Storage Group] *******************************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [
            {
                "cap_gb": 1,
                "num_vols": 1
            },
            {
                "cap_gb": 2,
                "num_vols": 2
            }
        ],
        "message": [
            "SG Ansible_SG_testing already exists",
            "SLO of SG Ansible_SG_testing already Diamond",
            "1 volume(s) of 2 GB added"
        ],
        "sg_volumes": [
            {
                "cap_gb": 2.0,
                "vol_name": "DATA",
                "volumeId": "000F5",
                "wwn": "60000970000297800941533030304635"
            },
            {
                "cap_gb": 1.0,
                "vol_name": "REDO",
                "volumeId": "000F6",
                "wwn": "60000970000297800941533030304636"
            },
            {
                "cap_gb": 2.0,
                "vol_name": "NEW_DATA",   <<  **The "good" vol_name has been applied**
                "volumeId": "000F7",
                "wwn": "60000970000297800941533030304637"
            }
        ],
        "storagegroup_name": "Ansible_SG_testing"
    }
}

TASK [Renaming Storage Group from Ansible_SG_testing to New_Ansible_SG_testing] **************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "lun_request": [
            {
                "cap_gb": 1,
                "num_vols": 1
            },
            {
                "cap_gb": 2,
                "num_vols": 2
            }
        ],
        "message": [
            "SG renamed to New_Ansible_SG_testing"
        ],
        "sg_volumes": [
            {
                "cap_gb": 2.0,
                "vol_name": "DATA",
                "volumeId": "000F5",
                "wwn": "60000970000297800941533030304635"
            },
            {
                "cap_gb": 1.0,
                "vol_name": "REDO",
                "volumeId": "000F6",
                "wwn": "60000970000297800941533030304636"
            },
            {
                "cap_gb": 2.0,
                "vol_name": "NEW_DATA",
                "volumeId": "000F7",
                "wwn": "60000970000297800941533030304637"
            }
        ],
        "storagegroup_name": "New_Ansible_SG_testing"
    }
}

TASK [Deleting Storage Group only volumes will be not deleted] *******************************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "storagegroup_detail": {
        "message": [
            "SG New_Ansible_SG_testing has been deleted"
        ],
        "storagegroup_name": "New_Ansible_SG_testing"
    }
}

PLAY RECAP ***********************************************************************************************************************************************
localhost                  : ok=14   changed=5    unreachable=0    failed=0

**Comment by rawstorage** [comment]
Julien, I've retested this with the newer versions and can't reproduce.  Seems ok now.
