### ISSUE TITLE
No handlers could be found for logger "PyU4V.rest_requests"

### ISSUE THREAD

**Issue by ravitejajyosula** [rawstorage/dellemcpmax_ansible#49]
Hi 

I am facing the following issue when I use this module in playbook and run the playbook in AWX. I am able to run same via commad line like ansible-playbook plyabook.yml but when i run through awx I face this issue. 

Error:
"module_stderr": "No handlers could be found for logger \"PyU4V.rest_requests\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dellpmax_createhost_payload_8zBOaH/__main__.py\", line 168, in <module>\n  File \"/tmp/ansible_dellpmax_createhost_payload_8zBOaH/__main__.py\", line 150, in main\n  File \"/usr/lib/python2.7/site-packages/PyU4V/provisioning.py\", line 148, in get_host_list\n    self.array_id, SLOPROVISIONING, 'host', params=filters)\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 321, in get_resource\n    return self.get_request(target_uri, resource_type, kwargs.get('params'))\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 277, in get_request\n    self.check_status_code_success(operation, sc, message)\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 167, in check_status_code_success\n    data=exception_message)\nPyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error get host. The status code received is None and the message is None.\n",

**Comment by jbrt** [comment]
Hello,

These modules are coded with a Python 3 first support in mind. For running them into AWX, you have to follow these prerequisites :

- Use a recent version of AWX (4.0.0) because version under 4.0 are not Python 3 compliant 
- Create a custom virtual environment into AWX running Python 3 (with modules dependencies PyU4V)
- Use this custom VENV with your AWX templates 

Regards,

**Comment by jbrt** [comment]
Hi @ravitejajyosula,

Did you fixed your problem with the previous mentioned tips ? 
Can we close this issue ?

Regards,

**Comment by ravitejajyosula** [comment]
I resolved the issue by changing the python version to 3.  Thanks @jbrt for your help.

**Comment by jbrt** [comment]
You're welcome @ravitejajyosula
